//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTC.Utils.Utils {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UtilsCResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilsCResource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTC.Utils.Utils.UtilsCResource", typeof(UtilsCResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} {1};.
        /// </summary>
        public static string Declare {
            get {
                return ResourceManager.GetString("Declare", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu {0} {1} = {2};.
        /// </summary>
        public static string DeclareAndInput {
            get {
                return ResourceManager.GetString("DeclareAndInput", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Main.c.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu if({0}){ {1} }else{ {2} }.
        /// </summary>
        public static string IfElse {
            get {
                return ResourceManager.GetString("IfElse", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu #include &lt;stdio.h&gt;.
        /// </summary>
        public static string IncludeStdio {
            get {
                return ResourceManager.GetString("IncludeStdio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu while({0}){{1}}.
        /// </summary>
        public static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu int main(){{0} return 0;}.
        /// </summary>
        public static string MainMethod {
            get {
                return ResourceManager.GetString("MainMethod", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu printf(&quot;%c&quot;, {0});.
        /// </summary>
        public static string PrintfChar {
            get {
                return ResourceManager.GetString("PrintfChar", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu printf(&quot;%lf&quot;, {0});.
        /// </summary>
        public static string PrintfDouble {
            get {
                return ResourceManager.GetString("PrintfDouble", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu printf(&quot;%f&quot;, {0});.
        /// </summary>
        public static string PrintfFloat {
            get {
                return ResourceManager.GetString("PrintfFloat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu printf(&quot;%d&quot;, {0});.
        /// </summary>
        public static string PrintfInt {
            get {
                return ResourceManager.GetString("PrintfInt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu printf(&quot;%li&quot;, {0});.
        /// </summary>
        public static string PrintfLong {
            get {
                return ResourceManager.GetString("PrintfLong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu printf({0});.
        /// </summary>
        public static string PrintfString {
            get {
                return ResourceManager.GetString("PrintfString", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu scanf(&quot;%c&quot;, &amp;{0});.
        /// </summary>
        public static string ScanfChar {
            get {
                return ResourceManager.GetString("ScanfChar", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu scanf(&quot;%lf&quot;, &amp;{0});.
        /// </summary>
        public static string ScanfDouble {
            get {
                return ResourceManager.GetString("ScanfDouble", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu scanf(&quot;%f&quot;, &amp;{0});.
        /// </summary>
        public static string ScanfFloat {
            get {
                return ResourceManager.GetString("ScanfFloat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu scanf(&quot;%d&quot;, &amp;{0});.
        /// </summary>
        public static string ScanfInt {
            get {
                return ResourceManager.GetString("ScanfInt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu scanf(&quot;%li&quot;, &amp;{0});.
        /// </summary>
        public static string ScanfLong {
            get {
                return ResourceManager.GetString("ScanfLong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu s.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
